markdown:         kramdown
highlighter:      rouge

# Setup
title:            "RCDS" 
tagline:          "Environment and Society: Data Sciences for the 21st Century"
description:      "Reproducible and Collaborative Data Science"
url:              "https://ds421.github.io/rcds"
baseurl:          "/rcds"

author:
  name:           "Carl Boettiger"
  url:            "http://carlboettiger.info"

github:
  repo:           "https://github.com/ds421/rcds"

destination: "../docs/"

## Don't render .Rmd files without compiling R
exclude:
  - "*.Rmd"

