# Dependencies
markdown:         kramdown 
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Reproducible and Collaborative Data Science' 
tagline:          'Environment and Society: Data Sciences for the 21st Century'
description:      'A UC Berkeley graduate student course in data science'
url:              https://ds421.github.com/rcds
baseurl:          /

author:
  name:           'Carl Boettiger'
  url:            http://carlboettiger.info

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ds421/rcds
