markdown:         kramdown
highlighter:      rouge

kramdown:
    input:        GFM

permalink:        pretty

# Setup
title:            'RCDS' 
tagline:          'Environment and Society: Data Sciences for the 21st Century'
description:      'Reproducible and Collaborative Data Science'
url:              'https://ds421.github.com/rcds'
baseurl:          '/rcds'

author:
  name:           'Carl Boettiger'
  url:            'http://carlboettiger.info'

github:
  repo:           'https://github.io/ds421/rcds'

collections: 
  main:
    output: true
    permalink: /:name
  lessons:
    output: true

